quarkus.swagger-ui.always-include=true
quarkus.http.host=0.0.0.0

# ── Credenciales por defecto (dev local) ──
# En K8s estas se sobreescriben con Vault via SMALLRYE_CONFIG_LOCATIONS=/vault/secrets/db
quarkus.datasource.username=tc-user
quarkus.datasource.password=tc-pass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/tc-test
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql